version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mahder
      POSTGRES_DB: document
    ports:
      - "5433:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: mahder
      DB_DATABASE: document
      NODE_ENV: production
      PORT: 3000

volumes:
  postgres-data:
